config/routes.rb
Rails.application.routes.draw do
  resources :places do
    resources :place_ratings, only: [:new, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "places#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/place.rb
class Place < ApplicationRecord
  delegate :x, to: :lonlat
  delegate :y, to: :lonlat

  has_many :place_ratings, dependent: :destroy
end

app/models/place_rating.rb
class PlaceRating < ApplicationRecord
  belongs_to :place
  validates :rating, presence: true, inclusion: { in: (0..5).to_a }
  after_create :set_avg_rating

  def set_avg_rating
    place_ratings_count = place.place_ratings.count
    sum_of_max_rating_count = place_ratings_count * 5
    sum_of_rating = place.place_ratings.sum(:rating)

    avg = (sum_of_rating * 5) / sum_of_max_rating_count

    place.update(avg_rating: avg)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/place_ratings_controller.rb
class PlaceRatingsController < ApplicationController
  before_action :set_place, only: %i[ new create ]

  # GET /places/new
  def new
    @place_rating = @place.place_ratings.new
  end

  # POST /places or /places.json
  def create
    @place_rating = @place.place_ratings.new(place_params)

    respond_to do |format|
      if @place_rating.save
        format.html { redirect_to place_url(@place), notice: "Place rating was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place_rating.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find_by(id: params[:place_id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place_rating).permit(:rating)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    condition = []
    if params[:search].present?
      condition << "lower(name) like (?)"
      condition << "%#{params[:search].downcase}%"
    end
    @places = Place.all.where(condition)
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to place_url(@place), notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_url(@place), notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :description, :lonlat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGisStarter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.12.0/mapbox-gl.css' rel='stylesheet' />
  </head>

  <body>
    <div id="root"></div>
    <%= yield %>
  </body>
</html>

app/views/place_ratings/_form.html.erb
<%= form_for(place_rating, url: path, method: :post) do |form| %>
  <% if place_rating.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(place_rating.errors.count, "error") %> prohibited this place_rating from being saved:</h2>

      <ul>
        <% place_rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/place_ratings/edit.html.erb
<h1>Editing place</h1>
<%= render "form", place_rating: @place_rating %>
<br>
<div>
  <%= link_to "Back to places", places_path %>
</div>

app/views/place_ratings/new.html.erb
<h1>New place rating</h1>

<%= render "form", place_rating: @place_rating, path: place_place_ratings_path %>

<br>

<div>
  <%= link_to "Back to places", places_path %>
</div>

app/views/places/_form.html.erb
<%= form_with(model: place) do |form| %>
  <% if place.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :lonlat, style: "display: block" %>
    <%= form.text_field :lonlat %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/places/_place.html.erb
<div id="<%= dom_id place %>">
  <p>
    <strong>Name:</strong>
    <%= place.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= place.description %>
  </p>

  <p>
    <strong>Lonlat:</strong>
    <%= place.lonlat %>
  </p>

  <p>
    <strong>AVG:</strong>
    <%= place.avg_rating %>
  </p>
</div>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render "form", place: @place %>

<br>

<div>
  <%= link_to "Show this place", @place %> |
  <%= link_to "Back to places", places_path %>
</div>

app/views/places/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Places</h1>
<%= form_tag(places_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag "Search" %>
<% end %>
<div id="places">
  <% @places.each do |place| %>
    <%= render place %>
    <p>
      <%= link_to "Show this place", place %>
    </p>
  <% end %>
</div>

<%= link_to "New place", new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render "form", place: @place %>

<br>

<div>
  <%= link_to "Back to places", places_path %>
</div>

app/views/places/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @place %>

<div>
  <%= link_to "Add rating to this place", new_place_place_rating_path(place_id: @place.id) %> |
  <%= link_to "Edit this place", edit_place_path(@place) %> |
  <%= link_to "Back to places", places_path %>

  <%= button_to "Destroy this place", @place, method: :delete %>
</div>